name: PluginHider
version: '${project.version}'
main: sryxen.plugins.pluginhider.PluginHider
api-version: '1.20'
authors: [Sryxen]
description: Plugin that helps in hiding the plugins installed on the server.

commands:
  pl:
    description: Hide plugins command
    usage: /pl
    aliases: [pluginhide]
    permission: pluginhider.view